# Generated by Django 4.1.5 on 2023-02-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Введите название города', max_length=30, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(help_text='Ссылка на квартиру', max_length=150)),
                ('room', models.IntegerField(help_text='Количество комнат')),
                ('region', models.CharField(help_text='Район', max_length=100, null=True)),
                ('address', models.CharField(help_text='Адресс', max_length=150, null=True)),
                ('price', models.IntegerField(help_text='Цена', null=True)),
                ('city', models.ForeignKey(help_text='Выберите город', on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='Город')),
            ],
        ),
    ]
