# Generated by Django 4.1.5 on 2023-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.CharField(blank=True, help_text='Адресс', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='price',
            field=models.IntegerField(blank=True, help_text='Цена', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='region',
            field=models.CharField(blank=True, help_text='Район', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='room',
            field=models.IntegerField(blank=True, help_text='Количество комнат'),
        ),
    ]
