# Generated by Django 4.1.5 on 2023-02-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_link_address_alter_link_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='room',
            field=models.IntegerField(blank=True, help_text='Количество комнат', null=True),
        ),
    ]
