# Generated by Django 4.1.5 on 2023-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_link_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='room',
            field=models.CharField(blank=True, help_text='Количество комнат', max_length=100, null=True),
        ),
    ]
