# Generated by Django 4.1.5 on 2023-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_alter_link_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='price',
            field=models.IntegerField(blank=True, help_text='Цена', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='room',
            field=models.IntegerField(blank=True, help_text='Количество комнат', null=True),
        ),
    ]
