# Generated by Django 4.1.5 on 2023-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='address',
            field=models.CharField(help_text='Адресс', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='price',
            field=models.IntegerField(help_text='Цена', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='region',
            field=models.CharField(help_text='Район', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='room',
            field=models.IntegerField(default=1, help_text='Количество комнат', max_length=1),
            preserve_default=False,
        ),
    ]
