# Generated by Django 4.1.5 on 2023-02-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_apartment', '0002_link_address_link_price_link_region_link_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='price',
            field=models.IntegerField(help_text='Цена', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='room',
            field=models.IntegerField(help_text='Количество комнат'),
        ),
    ]
