# Generated by Django 4.1.5 on 2023-02-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finding_apartment', '0003_alter_link_price_alter_link_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
